# docker-build.yml
name: Build Docker on Release

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Extract version parts
        run: |
          VERSION=${TAG#v}
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV
          echo "VERSION_MAJOR=${MAJOR}" >> $GITHUB_ENV
          echo "VERSION_MINOR=${MAJOR}.${MINOR}" >> $GITHUB_ENV

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/silverminer007/warehouse-backend:latest
            ghcr.io/silverminer007/warehouse-backend:${{ env.VERSION }}
            ghcr.io/silverminer007/warehouse-backend:${{ env.VERSION_MINOR }}
            ghcr.io/silverminer007/warehouse-backend:${{ env.VERSION_MAJOR }}
